import streamlit as st
import pandas as pd
import numpy as np
import requests
from sklearn.ensemble import IsolationForest

# 1. Page Configuration: Wide Layout & Page Title
st.set_page_config(
    page_title="AuditIQ - Step 5 (AI Auditor Connected)",
    layout="wide",
    page_icon="🔍"
)

# Sidebar controls
st.sidebar.title("AuditIQ Controls")
st.sidebar.markdown("---")
st.sidebar.header("⚙️ View Controls & Filters")
view_option = st.sidebar.radio(
    "Select View Mode:",
    ["Flagged Anomalies Only", "All Transactions", "Anomaly Summary & Metrics"],
    index=0
)

contamination = st.sidebar.slider(
    "Isolation Forest Contamination",
    min_value=0.01, max_value=0.20, value=0.05, step=0.01,
    help="Baseline percentage threshold for ML outlier detection."
)

st.sidebar.markdown("---")
st.sidebar.header("🤖 AI Auditor Settings")
colab_url = st.sidebar.text_input(
    "Colab Ngrok API URL",
    value="https://reflux-jogger-unmatched.ngrok-free.dev"
)
st.sidebar.caption("Enter the public Ngrok endpoint generated by your Google Colab backend server.")

st.sidebar.markdown("---")
st.sidebar.info("📌 **Audit Rules & Risk Weights:**\n"
                "- Statistical Outlier: **+4 pts**\n"
                "- Missing Approval: **+3 pts**\n"
                "- Duplicate Vendor Payment (< 30 Days): **+3 pts**\n"
                "- Weekend Transaction: **+2 pts**\n"
                "- Large Round Number (> $10k): **+2 pts**\n\n"
                "*(Max score strictly capped at 10)*")

# Title and header description
st.title("AuditIQ - POC Step 5")
st.subheader("Data Ingestion, Anomaly Detection, Risk Scoring & Colab LLM Integration")
st.markdown("Upload transactional CSV files for automated schema verification, ML outlier detection, rule-based audit checks, weighted risk scoring (1-10), and real-time AI 5C Finding generation via Google Colab.")

# 2. Required Schema Definition
REQUIRED_COLUMNS = ['date', 'amount', 'vendor', 'account_code', 'approved_by', 'department']

def calculate_risk_score(reasons_list: list) -> int:
    """
    Calculates weighted risk score from 1 to 10 based on triggered audit checks.
    Weights:
    - Statistical Outlier (Isolation Forest): +4
    - Missing Approval: +3
    - Duplicate Vendor Payment (< 30 Days): +3
    - Weekend Transaction: +2
    - Large Round Number (> $10,000): +2
    """
    if not reasons_list:
        return 0
    
    unique_r = set(reasons_list)
    score = 0
    if "Statistical Outlier (Isolation Forest)" in unique_r:
        score += 4
    if "Missing Approval" in unique_r:
        score += 3
    if "Duplicate Vendor Payment (< 30 Days)" in unique_r:
        score += 3
    if "Weekend Transaction" in unique_r:
        score += 2
    if "Large Round Number (> $10,000)" in unique_r:
        score += 2

    return min(10, max(1, score))

def run_anomaly_detection_pipeline(df_in: pd.DataFrame, contamination_rate: float = 0.05) -> pd.DataFrame:
    """
    Evaluates input DataFrame and adds 'is_anomalous' (bool), 'risk_score' (1-10 int), and 'anomaly_reasons' (str) columns.
    Uses IsolationForest ML outlier detection + 4 Rule-Based Audit Checks + Weighted Risk Scoring.
    """
    df = df_in.copy()
    
    # Initialize array of reason lists for each row
    reasons = [[] for _ in range(len(df))]
    
    # Create helper numeric and datetime columns
    df['parsed_date'] = pd.to_datetime(df['date'], errors='coerce')
    df['numeric_amount'] = pd.to_numeric(df['amount'], errors='coerce').fillna(0.0)
    
    # A. Machine Learning Outlier Detection (IsolationForest)
    if len(df) > 0:
        try:
            amounts_2d = df[['numeric_amount']].values
            iso_forest = IsolationForest(contamination=contamination_rate, random_state=42)
            preds = iso_forest.fit_predict(amounts_2d)
            
            for idx, pred in enumerate(preds):
                if pred == -1:
                    reasons[idx].append("Statistical Outlier (Isolation Forest)")
        except Exception as e:
            st.warning(f"Note: IsolationForest execution notice: {e}")

    # B. Rule-Based Audit Checks
    
    # Check 1: Duplicate Payments (same vendor & amount within 30 days)
    for idx, row in df.iterrows():
        v = row['vendor']
        amt = row['numeric_amount']
        dt = row['parsed_date']
        
        if pd.notnull(v) and pd.notnull(dt) and amt > 0:
            # Matches same vendor and same amount (excluding current row)
            matches = df[
                (df.index != idx) & 
                (df['vendor'] == v) & 
                (np.isclose(df['numeric_amount'], amt)) & 
                (df['parsed_date'].notnull())
            ]
            for _, match in matches.iterrows():
                diff_days = abs((dt - match['parsed_date']).days)
                if diff_days <= 30:
                    reasons[idx].append("Duplicate Vendor Payment (< 30 Days)")
                    break

    # Check 2: Large Round Numbers (amount >= 10,000 AND round number)
    for idx, row in df.iterrows():
        amt = row['numeric_amount']
        if amt >= 10000:
            raw_amt_str = str(row['amount']).strip()
            # Check if amount is round (e.g. ends in .00, .0 or divisible by 1,000/100 with zero decimals)
            is_round = (amt % 100 == 0) or (amt % 1000 == 0) or raw_amt_str.endswith('.00') or raw_amt_str.endswith('.0')
            if is_round:
                reasons[idx].append("Large Round Number (> $10,000)")

    # Check 3: Weekend Transactions (Saturday or Sunday)
    for idx, row in df.iterrows():
        dt = row['parsed_date']
        if pd.notnull(dt):
            if dt.weekday() in [5, 6]:  # 5 = Saturday, 6 = Sunday
                reasons[idx].append("Weekend Transaction")

    # Check 4: Missing Approver (null, blank, NaN, or whitespace)
    for idx, row in df.iterrows():
        approver = row.get('approved_by')
        if pd.isna(approver) or approver is None or str(approver).strip() == '' or str(approver).lower() in ['nan', 'null', 'none']:
            reasons[idx].append("Missing Approval")

    # Format output columns & compute Step 3 risk score
    is_anomalous = [len(r) > 0 for r in reasons]
    risk_scores = [calculate_risk_score(r) for r in reasons]
    formatted_reasons = [", ".join(sorted(set(r))) if len(r) > 0 else "Normal" for r in reasons]
    
    df['is_anomalous'] = is_anomalous
    df['risk_score'] = risk_scores
    df['anomaly_reasons'] = formatted_reasons
    
    # Clean up temporary helper columns
    df = df.drop(columns=['parsed_date', 'numeric_amount'])
    
    return df

def apply_risk_score_styling(df_to_style: pd.DataFrame):
    """
    Applies Pandas background styling to the 'risk_score' column:
    - Red for scores 8-10 (High Risk)
    - Yellow/Orange for scores 5-7 (Medium Risk)
    - Green for scores below 5 (Low Risk)
    """
    def style_risk(val):
        if not isinstance(val, (int, float, np.number)):
            return ''
        if val >= 8:
            return 'background-color: #f8d7da; color: #721c24; font-weight: bold;'
        elif val >= 5:
            return 'background-color: #fff3cd; color: #856404; font-weight: bold;'
        elif val > 0:
            return 'background-color: #d4edda; color: #155724; font-weight: bold;'
        return ''

    styler = df_to_style.style
    if hasattr(styler, 'map'):
        return styler.map(style_risk, subset=['risk_score'])
    else:
        return styler.applymap(style_risk, subset=['risk_score'])

# 3. File Uploader Widget (Accepts CSV files only)
uploaded_file = st.file_uploader("Upload CSV file", type=["csv"], help="Upload an audit sample CSV file to validate schema and run anomaly pipeline.")

if uploaded_file is not None:
    try:
        # Read CSV into Pandas DataFrame
        df_raw = pd.read_csv(uploaded_file)
        
        # 4. Validate Schema
        uploaded_cols = list(df_raw.columns)
        missing_cols = [col for col in REQUIRED_COLUMNS if col not in uploaded_cols]
        
        # If any columns are missing, halt execution and display strict st.error
        if missing_cols:
            st.error(f"❌ Schema Validation Error: The uploaded CSV file is missing required columns:\n\n" + 
                     "\n".join([f"- `{col}`" for col in missing_cols]))
            st.warning(f"Expected schema: `{REQUIRED_COLUMNS}`\n\nFound columns: `{uploaded_cols}`")
            st.stop()
            
        # 5. Validation Success Response & Anomaly Pipeline
        st.success("✅ Schema Validation Successful! Running Step 5 Anomaly Detection, Risk Scoring & Colab AI Pipeline...")
        
        # Execute Anomaly Pipeline
        df_analyzed = run_anomaly_detection_pipeline(df_raw, contamination_rate=contamination)
        
        # Filter down to anomalous transactions
        flagged_df = df_analyzed[df_analyzed['is_anomalous'] == True]
        total_count = len(df_analyzed)
        anomaly_count = len(flagged_df)
        anomaly_pct = (anomaly_count / total_count * 100) if total_count > 0 else 0.0

        # Summary Metrics Row
        m1, m2, m3, m4 = st.columns(4)
        with m1:
            st.metric(label="Total Transactions", value=f"{total_count:,}")
        with m2:
            st.metric(label="Anomalies Flagged", value=f"{anomaly_count:,}", delta=f"{anomaly_pct:.1f}% Flagged", delta_color="inverse")
        with m3:
            st.metric(label="Clean Transactions", value=f"{total_count - anomaly_count:,}")
        with m4:
            st.metric(label="Unique Vendors", value=f"{df_analyzed['vendor'].nunique():,}")

        st.divider()

        # Display Based on View Option
        if view_option == "Flagged Anomalies Only":
            st.subheader("🚩 Flagged Anomaly Report (Sorted by Risk Score)")
            st.markdown(f"Displaying **{anomaly_count}** flagged transactions requiring auditor review, sorted by highest risk score first.")
            
            if anomaly_count > 0:
                # Sort flagged anomalies by risk_score descending (highest score 10 at top)
                flagged_sorted = flagged_df.sort_values(by='risk_score', ascending=False)
                
                # Apply Pandas background color-coding for risk_score
                styled_flagged = apply_risk_score_styling(flagged_sorted)
                
                # Render color-coded, sorted dataframe
                st.dataframe(styled_flagged, use_container_width=True, height=350)
                
                # Download flagged report
                csv_data = flagged_sorted.to_csv(index=False).encode('utf-8')
                st.download_button(
                    label="📥 Download Flagged Anomaly Report (CSV)",
                    data=csv_data,
                    file_name="flagged_audit_anomalies_risk_scored.csv",
                    mime="text/csv",
                )

                # Interactive AI Finding Generation Section
                st.markdown("---")
                st.subheader("🤖 AI 5C Audit Finding Generator")
                st.markdown("Select any flagged transaction below to trigger the Big 4 Senior Auditor LLM backend hosted on Google Colab.")

                for index, row in flagged_sorted.iterrows():
                    vendor_name = str(row["vendor"])
                    try:
                        amt_val = float(row["amount"])
                        amt_str = f"${amt_val:,.2f}"
                    except Exception:
                        amt_val = 0.0
                        amt_str = f"${row['amount']}"
                    
                    risk_val = row.get("risk_score", 0)
                    expander_title = f"🤖 Generate AI 5C Finding — Vendor: {vendor_name} ({amt_str})"
                    
                    with st.expander(expander_title):
                        c1, c2 = st.columns([3, 1])
                        with c1:
                            st.write(f"**Department:** {row.get('department', 'N/A')} | **Date:** {row.get('date', 'N/A')} | **Approved By:** {row.get('approved_by', 'N/A')}")
                            st.write(f"**Triggered Anomaly Flags:** `{row.get('anomaly_reasons', 'N/A')}`")
                        with c2:
                            st.metric(label="Risk Score", value=f"{risk_val}/10")
                        
                        btn_key = f"btn_{index}"
                        if st.button("Run AI Senior Audit", key=btn_key):
                            endpoint = f"{colab_url.rstrip('/')}/generate_finding"
                            payload = {
                                "amount": float(row["amount"]),
                                "vendor": str(row["vendor"]),
                                "department": str(row["department"]),
                                "anomaly_reasons": str(row["anomaly_reasons"])
                            }
                            
                            with st.spinner("Querying Big 4 Senior Auditor LLM..."):
                                try:
                                    response = requests.post(endpoint, json=payload, timeout=25)
                                    if response.status_code == 200:
                                        res_json = response.json()
                                        # Render returned 5C Audit Finding
                                        finding_content = (
                                            res_json.get("finding") or 
                                            res_json.get("result") or 
                                            res_json.get("5c_finding") or 
                                            str(res_json)
                                        )
                                        st.success("✅ 5C Audit Finding Generated Successfully!")
                                        st.markdown("### 📋 Big 4 Senior Auditor 5C Finding Report")
                                        st.info(finding_content)
                                    else:
                                        st.error("Failed to connect to Colab LLM Server. Please check if your Google Colab notebook cell is running and the Ngrok URL is correct.")
                                except Exception:
                                    st.error("Failed to connect to Colab LLM Server. Please check if your Google Colab notebook cell is running and the Ngrok URL is correct.")

            else:
                st.info("🎉 No anomalies detected in this dataset based on current rules.")

        elif view_option == "All Transactions":
            st.subheader("📋 Ingested Audit Transactions (All Rows)")
            st.markdown("All rows with appended `is_anomalous`, `risk_score`, and `anomaly_reasons` columns.")
            
            # Sort all transactions by risk_score descending
            df_analyzed_sorted = df_analyzed.sort_values(by='risk_score', ascending=False)
            styled_all = apply_risk_score_styling(df_analyzed_sorted)
            
            st.dataframe(styled_all, use_container_width=True, height=450)

        else: # Anomaly Summary & Metrics
            st.subheader("📊 Anomaly Breakdown & Audit Rules Analysis")
            
            # Count occurrences of each reason
            all_reasons = []
            for r in flagged_df['anomaly_reasons']:
                if r != "Normal":
                    all_reasons.extend([item.strip() for item in r.split(",")])
            
            if all_reasons:
                reason_counts = pd.Series(all_reasons).value_counts().reset_index()
                reason_counts.columns = ["Audit Check / Anomaly Rule", "Flag Count"]
                
                c1, c2 = st.columns([1, 1])
                with c1:
                    st.write("**Flags by Rule Type:**")
                    st.dataframe(reason_counts, use_container_width=True)
                with c2:
                    st.write("**Top Flagged Vendors:**")
                    top_vendors = flagged_df['vendor'].value_counts().reset_index()
                    top_vendors.columns = ["Vendor", "Anomalous Transaction Count"]
                    st.dataframe(top_vendors, use_container_width=True)
            else:
                st.info("No audit rules were triggered.")

    except Exception as e:
        st.error(f"An error occurred while parsing or processing the CSV file: {e}")
else:
    st.info("💡 Please upload a `.csv` file to perform schema validation and run Step 5 anomaly detection & AI risk scoring.")

